name: myenv
channels:
  - defaults
dependencies:
  - python=3.12
  - flask
  - pip
  - flask_cors
  - numpy
  - pandas
  - requests
  - scikit-learn
  - scipy
  - gunicorn
  - matplotlib
  - sqlalchemy
  - psycopg2
  - jinja2
  - beautifulsoup4
  - lxml
  - anyio
  - joblib
  - jsonschema
  - pytz
  - pyyaml
  - werkzeug
  - openai
  - pip:
      - python-dotenv
