name: Build and deploy Python app to Azure Web App - myfitnessai

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Navigate to backend directory and set up environment
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: 'https://fitnessaicoach.azurewebsites.net/'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: List files after unzipping
        run: ls -R

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'fitnessaicoach'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B799F559D19640A3BAAB4FCB0DE400E4 }}

      - name: Verify deployment
        run: |
          echo "Deployment complete. Checking deployed files..."
          curl -I https://fitnessaicoach.azurewebsites.ner


