name: Build and deploy Python app to Azure Web App - myfitnessaicoach-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          python-version: '3.10'
      
      - name: Create conda environment
        run: |
          conda create -n myenv python=3.10 -y
          source activate myenv
          conda install -y --file requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: List files before zipping
        run: ls -al

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*"

      - name: List files after zipping
        run: ls -al

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: List files after download
        run: ls -al

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: List files after unzipping
        run: ls -al

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'myfitnessaicoach-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CC592A1A03AC4D13B3D1E9F8026DB51C }}
